# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    #Indicamos en que entidad se va a utilizar este protocolo de cifrado
    #Y despues inidicamos el algoritmo de cifrado  que es bcrypt y despues indicamos cuantas veces queremos que se vuelva a cirfrar la contraseña ya cifrada
    encoders:
        BackendBundle\Entity\User:
            algorithm: bcrypt
            cost: 4
            
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    #Que entidad va a ser la que nos va a proporcionar la autenti¡ficacion del usuario
    providers:
        user_db_provider:
            entity:
                class: BackendBundle:User
                property: email
     #Aqui indicamos cual va a ser el provider de Usuario, que entidad va a proveer de usuario a la autentificacion, la clase de la entida de Usuario y despues la propiedad que va aa usarse como username dentro de la autentificacion  


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
                #Aqui compruba si el usuario ya existe y si las credenciales son correctas...
            logout:
                path: logout
                target: /
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        #Esto significa que a /login y a /register solo pueden acceder los usuarios no identificados
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        #Esto significa que a /.... solo pueden acceder los usuarios que tengan el role de user o admin
        - { path: ^/home, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/publication/remove, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/my-data, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/people, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/search, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/user, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/private-message, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/private-message/sended, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/private-message/notification/get, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/notifications, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/notifications/get, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/like, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/unlike, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/likes, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/follow, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/unfollow, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/following, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/followed, roles: [ROLE_USER, ROLE_ADMIN]}

         