# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    
    
#Vamos a cargar la extension de twig
    
    following.twig_extension:
        #Clase que va a ser la extension de twig
        class: AppBundle\Twig\FollowingExtension
        #La clase no va a ser publica ya que se va apoder utilizaar solamente dentro de AppBundle
        public: false
        arguments:
            #Le pasamos como arguments doctrine y le pasamos una instancia de doctrine que es un servicio que ya inyectar
            doctrine: "@doctrine"
        #Le pasamos como tags que es una twig.extension
        tags:
            - { name: twig.extension }
            
    long_time.twig_extension:
         class: AppBundle\Twig\LongTimeExtension
         public: false
         tags:
             - { name: twig.extension }
             
    liked.twig_extension:
        #Clase que va a ser la extension de twig
        class: AppBundle\Twig\LikedExtension
        #La clase no va a ser publica ya que se va apoder utilizaar solamente dentro de AppBundle
        public: false
        arguments:
            #Le pasamos como arguments doctrine y le pasamos una instancia de doctrine que es un servicio que ya inyectar
            doctrine: "@doctrine"
        #Le pasamos como tags que es una twig.extension
        tags:
            - { name: twig.extension }

    user_stats.twig_extension:
        #Clase que va a ser la extension de twig
        class: AppBundle\Twig\UserStatsExtension
        #La clase no va a ser publica ya que se va apoder utilizaar solamente dentro de AppBundle
        public: false
        arguments:
            #Le pasamos como arguments doctrine y le pasamos una instancia de doctrine que es un servicio que ya inyectar
            doctrine: "@doctrine"
        #Le pasamos como tags que es una twig.extension
        tags:
            - { name: twig.extension }
            
            
    get_user.twig_extension:
        #Clase que va a ser la extension de twig
        class: AppBundle\Twig\GetUserExtension
        #La clase no va a ser publica ya que se va apoder utilizaar solamente dentro de AppBundle
        public: false
        arguments:
            #Le pasamos como arguments doctrine y le pasamos una instancia de doctrine que es un servicio que ya inyectar
            doctrine: "@doctrine"
        #Le pasamos como tags que es una twig.extension
        tags:
            - { name: twig.extension }
    
    #Tenemos el servicio registrado y lo podemos utilizar en cualquiera de los controladores
    app.notification_service:
        #Le indicamos la clase del servicio
        class: AppBundle\Services\NotificationService
        #Le indicamos los argumentos para inyectarle el servicio de doctrine, el manager de doctrine
        arguments: ["@doctrine.orm.entity_manager"]