home_publications:
    path: /home
    defaults: { _controller: AppBundle:Publication:index }
##En defaults indicamos que Bundle va utilizar, que controlador va utilizar y que metodo va a utilizar
##Asi configuramos la ruta

remove_publication:
    path: /publication/remove/{id}
    defaults: { _controller: AppBundle:Publication:removePublication, id:null }
    ##La id que ponemos aqui es la que se recibe por parametro en el PublicacionController